-- MySQL Script generated by MySQL Workbench
-- Mon 05 Mar 2018 05:04:19 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TerraDrop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TerraDrop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TerraDrop` DEFAULT CHARACTER SET utf8 ;
USE `TerraDrop` ;

-- -----------------------------------------------------
-- Table `TerraDrop`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TerraDrop`.`User` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(48) NOT NULL,
  `Password` VARCHAR(48) NOT NULL,
  `DisplayName` VARCHAR(48) NOT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TerraDrop`.`TerraDrop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TerraDrop`.`TerraDrop` (
  `DropID` INT NOT NULL AUTO_INCREMENT,
  `Hidden` TINYINT(1) NOT NULL,
  `Latitude` DOUBLE NOT NULL,
  `Longitude` DOUBLE NOT NULL,
  `Title` VARCHAR(48) NOT NULL,
  `Message` VARCHAR(1024) NOT NULL,
  `UserID` INT NOT NULL,
  PRIMARY KEY (`DropID`),
  INDEX `fk_Drop_1_idx` (`UserID` ASC),
  CONSTRAINT `UserID_fk`
    FOREIGN KEY (`UserID`)
    REFERENCES `TerraDrop`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TerraDrop`.`Found`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TerraDrop`.`Found` (
  `UserID` INT NOT NULL,
  `DropID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `DropID`),
  INDEX `DropID_fk_idx` (`DropID` ASC),
  CONSTRAINT `UserID_F_fk`
    FOREIGN KEY (`UserID`)
    REFERENCES `TerraDrop`.`User` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DropID_F_fk`
    FOREIGN KEY (`DropID`)
    REFERENCES `TerraDrop`.`TerraDrop` (`DropID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
